### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-3-Pochupryn** [UMSF-K13-3-Pochupryn/K13-N-Pochupryn-MainProject1#1]
![default](https://cloud.githubusercontent.com/assets/19716102/15757440/40df9814-290e-11e6-8973-2a1b95d4b5a5.JPG)

**Comment by smoktii-igov** [comment]
необходимо назначить на меня ишью + указать лайблы

**Comment by smoktii-igov** [comment]
Ок
